defaults:
  - blob_descriptor_base
  - dgx
  - _self_

model:
  name: BlobDescriptorNoStride
  params:
    scale_factors: [16.0]
    in_channels: 1

training:
  batch_size: 1024
  dataset:
    params:
      patch_type: cartesian
      patch_scale_factors: [16.0]
      extraction_batch_size: 512
  optimizer:
    name: AdamW

validation:
  dataset:
    params:
      patch_type: cartesian
      patch_scale_factors: [16.0]
      extraction_batch_size: 512
