defaults:
  - _self_
  - model: affine_feature_net_one
training:
  batch_size: 1
  num_epochs: 100
  feature_sampling:
    num_features: 100
    # stride: 12
    # detector: "harris"
  dataset:
    suffix: "train"
    params:
      image_size: [256, 256]
  augmentation:
    color_jitter:
      brightness: 0.5
      contrast: 0.5
      saturation: 0.5
      hue: 0.5
    gaussian_blur:
      kernel_size: 5
      sigma: 1.0
    gaussian_noise:
      mean: 0.0
      sigma: 0.1
validation:
  batch_size: 1
  dataset:
    suffix: "test"
    params:
      image_size: [256, 256]
  feature_sampling:
    num_features: 10
logging:
  dir: "./data/logs"
  interval: 100
