defaults:
  - config
  - override model: affine_feature_net_one
  - _self_

training:
  optimizer:
    scale_space:
      name: "adam"
      params:
        lr: 1e-3
        decay: 5e-5
        momentum: 0.9
        weight_decay: 1e-4
      scheduler:
        name: "mulistep"
        params:
          milestones: [20, 40]
          gamma: 0.1
    feature_net:
      name: "adamw"
      params:
        lr: 2e-3
      scheduler:
        name: "cosine"
  loss: npairs
