defaults:
  - detector_unet_dgx
  - _self_

training:
  image_batch_size: 8
  dataset:
    name: ColmapData
    params:
      images: /data/datasets/south-building
      image_size: [512, 512]
  num_epochs: 600
  batch_size: 30000
  loss:
    - name: Supcon
      report: true
  process_batch: process_batch_colmap_detector
  continue_from_checkpoint: /data/logs/detector_unet_step_1/checkpoints/epoch_009.pth
  optimizer:
    name: adamw
    params:
      lr: 1e-4
      weight_decay: 1e-4
validation:
  loss:
    - name: Contrastive
      params:
        contrastive_loss: fpr
  dataset:
    name: ColmapData
    params:
      images: /data/datasets/south-building
      image_size: [512, 512]
  batch_size: 30000
experiment_name: detector_unet_step_2_colmap
