defaults:
  - config
  - _self_

model:
  name: AffineFeatureNetCanonicalOne
  params:
    conv_depths: [16, 16, 32, 32, 64, 64]
    basic_block_params:
      option: B
    # scale_space:
    #   name: NeuralScaleSpaceSESN
    #   params:
    #     factor: 6.5
    #     num_scales: 4
    #     min_scale: 2.0
    #     effective_size: 5
    #   pretrained: /data/logs/scale_space_sesn_blobboards_homographic_rel_squared_2026_05_15_15_25_41/checkpoints/best.pth
    #   freeze: false

training:
  image_batch_size: 8
  process_batch: process_batch_colmap_detector
  dataset:
    name: KaggleHomographyData
    params:
      name: image-matching-challenge-2025
      image_size: [512, 512]
      num_boards: 80
      in_memory: false
      blobboard_params:
        cutoff: 2.0
      transform_params:
        scaling_amplitude: 0.05
        perspective_amplitude_x: 0.05
        perspective_amplitude_y: 0.05
        max_angle: "π / 8"
  loss:
    - name: SupCon
  optimizer:
    scale_space:
      name: adam
      model_params: scale_space
      params:
        lr: 1e-6
        weight_decay: 5e-5
      scheduler:
        name: multistep
        params:
          milestones: [20, 40]
          gamma: 0.1
    feature_net:
      name: adamw
      model_params:
        - feature_net
        - scale_gain
        - canonicalization_layer
      params:
        lr: 2e-3
      scheduler:
        name: cosine
        params:
          T_max: 50

validation:
  process_batch: process_batch_homographic_detector
  dataset:
    name: KaggleHomographyData
    params:
      in_memory: false
      name: image-matching-challenge-2025
      image_size: [512, 512]
      num_boards: 8
      blobboard_params:
        cutoff: 2.0
      transform_params:
        scaling_amplitude: 0.05
        perspective_amplitude_x: 0.05
        perspective_amplitude_y: 0.05
        max_angle: "π / 8"
  loss:
    - name: FPR95
