defaults:
  - detector_unet_dgx
  - _self_

training:
  num_epochs: 120
  loss:
    - name: ImageGeneration
      weight: 0.5
    - name: Reprojection
      weight: 0.02
    - name: Contrastive
    - name: NonSingular
      report: false
  epochs: 60
  continue_from_checkpoint: /data/logs/detector_unet_step_2_second_run/checkpoints/epoch_059.pth
  optimizer:
    name: adamw
    params:
      lr: 1e-4
      weight_decay: 1e-4
validation:
  loss:
    - name: Contrastive
      params:
        contrastive_loss: fpr
experiment_name: detector_unet_step_2
