defaults:
  - config
  - _self_

model:
  name: affine_feature_net_canonical_two
  params:
    conv_depths: [16, 16, 16, 16, 16, 32, 32, 32, 32, 32, 64, 64, 64, 64, 64]
    basic_block_params:
      option: B
    scales:
      factor: 6.5
      num_scales: 8
      min_scale: 2.0
training:
  dataset:
    name: blobboards_homographic
    params:
      image_size: [128, 128]
      num_boards: 80
      polarity: "random"
  loss:
    - name: reprojection
      params:
        distance_metric: euclidean
      weight: 1
    - name: geodesic
      weight: 1
  optimizer:
    name: adamw
    params:
      lr: 2e-3
    scheduler:
      name: cosine
      params:
        T_max: 50
validation:
  dataset:
    name: blobboards_homographic
    params:
      image_size: [128, 128]
      # num_boards: 8
      # polarity: "random"
  loss: img_gen
