defaults:
  - config
  - _self_

model:
  name: affine_feature_net_canonical_one
  params:
    conv_depths: [16, 16, 16, 16, 16, 32, 32, 32, 32, 32, 64, 64, 64, 64, 64]
    basic_block_params:
      option: B
    scale_space:
      name: scale_space_sesn
      params:
        factor: 6.5
        num_scales: 8
        min_scale: 2.0
        effective_size: 5
training:
  dataset:
    name: KaggleHomographyData
    params:
      name: image-matching-challenge-2025
      image_size: [256, 256]
      num_boards: 80
      blobboard_params:
        cutoff: 2.0
  loss:
    - name: img_gen
      params:
        distance_metric: mse
      weight: 1
  optimizer:
    scale_space:
      name: adam
      model_params: scale_space
      params:
        lr: 1e-3
        weight_decay: 5e-5
      scheduler:
        name: multistep
        params:
          milestones: [20, 40]
          gamma: 0.1
    feature_net:
      name: adamw
      model_params:
        - feature_net
        - scale_gain
      params:
        lr: 2e-3
      scheduler:
        name: cosine
        params:
          T_max: 50
validation:
  dataset:
    name: KaggleHomographyData
    params:
      name: image-matching-challenge-2025
      image_size: [256, 256]
      num_boards: 8
      blobboard_params:
        cutoff: 2.0
  loss: img_gen
