defaults:
  - config
  - _self_

model:
  name: NeuralScaleSpaceSESN
  params:
    factor: 12
    num_scales: 8
    min_scale: 1
    effective_size: 5
    scale_output_factor: 0.25

training:
  num_epochs: 120
  process_batch: process_batch_scale_colmap
  # continue_from_checkpoint: /data/logs/NeuralScaleSpaceSESN_SiftScaleLoss_2026_06_02_22_47_40/checkpoints/epoch_022.pth
  dataset:
    name: ColmapData
    params:
      images: /data/datasets/south-building
      image_size: [512, 512]
  loss: 
    - name: SiftScaleLoss
      report: true
  optimizer:
    name: adam
    params:
      lr: 1e-3
      weight_decay: 1e-4
    scheduler:
      name: multistep
      params:
        milestones: [40, 80]
        gamma: 0.1

validation:
  dataset:
    name: ColmapData
    params:
      images: /data/datasets/south-building
      image_size: [512, 512]
  loss: 
    - name: SiftScaleLoss
      report: true

logging:
  interval: 1
