defaults:
  - config
  - _self_

model:
  name: scale_space_sesn
  params:
    factor: 10.0
    num_scales: 10
    min_scale: 1.0
    effective_size: 5
training:
  dataset:
    name: blobboards_absolute_scale
    params:
      image_size: [64, 64]
      num_boards: 120
  optimizer:
    name: "adam"
    params:
      lr: 1e-3
      weight_decay: 1e-4
    scheduler:
      name: "mulistep"
      params:
        milestones: [20, 40]
        gamma: 0.1
  loss: "mse"
validation:
  dataset:
    name: blobboards_absolute_scale
    params:
      image_size: [256, 256]
      num_boards: 12
logging:
  interval: 1
